#!/bin/bash

# cpplox run tests script
# Alexander Dumais

start=`date +%s.%N`
(
   set -x;
   g++-9 -std=c++2a -Wall -o ./bin/test_scan_tokens -I../include/ ../src/debug.cpp ../src/run.cpp ../src/scanner.cpp ../src/token.cpp test_scan_tokens.cpp
)
end=`date +%s.%N`
runtime=$( echo "$end - $start" | bc -l )
echo "test_scan_keywords compile time: $runtime"

# run tests
./bin/test_scan_tokens
